spring:
  ai:
    openai:
      api-key: {api-key}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: mistralai/mistral-small-3.1-24b-instruct:free
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: debug