spring:
  ai:
    openai:
      api-key: {api-key}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: deepseek/deepseek-chat-v3-0324:free
    tools:
      observations:
        include-content: true
logging:
  level:
    org:
      springframework:
        ai:
          debug